Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(100,10,'Bike Chain');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(101,25,'Bearing');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(102,12.25,'Belt Drive');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(103,5,'Brake cable');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(104,7.75,'Head Tube');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(105,45,'Wheel');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(106,15,'Seat');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(107,11.50,'Skirt Guard');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(108,5,'Wingnut');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(109,2,'Toe Clips');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(110,55,'Hub Gear');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(112,30.01,'Chain Ring');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(113,12.30,'Bottom Bracket');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(114,4.75,'Grips');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(115,6,'Suspension');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(116,1.50,'Stems');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(117,8.15,'Cranksets');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(118,19,'Hubs');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(119,2.75,'Seat Clamps');
Insert into  `SalesPortal`.`Item` (Id,Price,Name) values(119,29,'Derailleur Hanger');

